# Generated by Django 4.1.3 on 2022-12-07 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_csvmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="csvmodel", name="additional", field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="csvmodel",
            name="phone_number",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
